//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departament
    {
        public int DepartamentId { get; set; }
        public string DepartamentName { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
